# Generated by Django 5.0.2 on 2024-05-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tel_number', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(default=None, max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('number', models.DecimalField(decimal_places=0, default=0, max_digits=256, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zipcode', models.DecimalField(decimal_places=0, default=0, max_digits=5, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(null=True)),
                ('error', models.CharField(max_length=100, null=True)),
                ('departments', models.ManyToManyField(blank=True, to='home.department')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(default=None, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('number', models.DecimalField(decimal_places=0, default=0, max_digits=256)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('city', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('departments', models.ManyToManyField(blank=True, to='home.department')),
            ],
        ),
    ]
