# Generated by Django 5.0.2 on 2024-05-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='leitung',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
