# Generated by Django 5.0.2 on 2024-05-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_department_leitung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='error',
        ),
    ]
